import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';

// import styles from '../styles/Home.module.css';
import { getSeasonsList } from '../libs/util';

interface Props {
  seasons: number[];
}

const Home: NextPage<Props> = ({ seasons }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Seasons</h1>

        <ul>
          {seasons.map(season => (
            <li key={season}>
              <Link href={`/season/${season}`}>
                <a>{season}</a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps<Props> = () => {
  return {
    props: {
      seasons: getSeasonsList(),
    },
  };
};

export default Home;
